import Groq from "groq-sdk";

export const generateBlogWithAI = async ({
  title,
  keywords,
  description,
}) => {
  const groq = new Groq({
    apiKey: process.env.GROQ_API_KEY,
  });

  const prompt = `
You are a professional blog writer and SEO content expert.

Generate a high-quality, engaging and SEO-friendly blog based on the following information.

Blog Title:
${title}

Keywords:
${keywords}

Description:
${description}

Requirements:

- Write a detailed and useful blog.
- Start with a strong introduction.
- Use proper headings and subheadings.
- Naturally include the provided keywords.
- Do not keyword-stuff.
- Keep the content simple, clear and easy to read.
- Use paragraphs where appropriate.
- Use bullet points or numbered lists where useful.
- Add examples where they improve the explanation.
- End with a useful conclusion.
- Do not mention that the content was generated by AI.

IMPORTANT OUTPUT FORMAT:

Return the complete blog as clean HTML only.

Use only these HTML tags:
<h1>, <h2>, <h3>, <p>, <ul>, <ol>, <li>, <strong>, <em>, <blockquote>, <table>, <thead>, <tbody>, <tr>, <th>, <td>

Rules for HTML output:

- Do NOT use Markdown.
- Do NOT use #, ##, ### for headings.
- Do NOT use ** or * for formatting.
- Do NOT create Markdown tables.
- Do NOT wrap the response inside \`\`\`html.
- Do NOT use \`\`\` code blocks.
- Do NOT include <html>, <head>, or <body> tags.
- Return ONLY the HTML blog content.
- Make sure the returned HTML is valid and properly structured.
`;

  const completion = await groq.chat.completions.create({
    model: "openai/gpt-oss-20b",

    messages: [
      {
        role: "system",
        content:
          "You are an expert SEO blog writer who creates natural, high-quality content and always follows the requested HTML output format.",
      },
      {
        role: "user",
        content: prompt,
      },
    ],

    temperature: 0.7,
    max_completion_tokens: 4000,
  });

  return completion.choices[0]?.message?.content || "";
};